// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebBanHang.Models.Entities;

public partial class Cart
{
    public int Id { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime LatestUpdate { get; set; }

    public int UserId { get; set; }

    public virtual ICollection<CartProduct> CartProduct { get; set; } = new List<CartProduct>();

    public virtual Users User { get; set; }
}