// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebBanHang.Models.Entities;

public partial class CartProduct
{
    public int Id { get; set; }

    public int CartId { get; set; }

    public int ProductId { get; set; }

    public short Quantity { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual Product Product { get; set; }
}