// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebBanHang.Models.Entities;

public partial class Introduce
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string ShortDescription { get; set; }
}