// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebBanHang.Models.Entities;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Avatar { get; set; }

    public int? CategoryId { get; set; }

    public int? TypeId { get; set; }

    public int? BrandId { get; set; }

    public string ShortDes { get; set; }

    public string FullDescription { get; set; }

    public double? Price { get; set; }

    public double? PriceDiscount { get; set; }

    public string Slug { get; set; }

    public bool? Deleted { get; set; }

    public bool? ShowOnHomePage { get; set; }

    public int? DisplayOrder { get; set; }

    public DateTime? CreatedOnUtc { get; set; }

    public DateTime? UpdatedOnUtc { get; set; }

    public int Stock { get; set; }

    public bool IsDelete { get; set; }

    public virtual ICollection<CartProduct> CartProduct { get; set; } = new List<CartProduct>();

    public virtual Category Category { get; set; }

    public virtual ICollection<Review> Review { get; set; } = new List<Review>();
}