// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebBanHang.Models.Entities;

public partial class VCart
{
    public int CartId { get; set; }

    public int UserId { get; set; }

    public string ProductName { get; set; }

    public short Quantity { get; set; }

    public double? Price { get; set; }

    public string Avatar { get; set; }
}